PYTHON-2673 Debug socket GC leak
When a retryable read retry succeeds and the resulting Cursor is garbage
collected soon after, the GC closes the pinned SocketInfo's underlying
socket instance.
ResourceWarning: unclosed <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 56018), raddr=('127.0.0.1', 8000)>

It appears to be a bug in CPython related to how the GC works when
collecting Exception objects.

Running Find
2021-06-10 11:22:31,202 INFO event_loggers [pool ('127.0.0.1', 8000)] connection check out started
2021-06-10 11:22:31,203 INFO event_loggers [pool ('127.0.0.1', 8000)][conn #1] connection created
2021-06-10 11:22:31,205 INFO event_loggers [pool ('127.0.0.1', 8000)][conn #1] connection setup succeeded
2021-06-10 11:22:31,205 INFO event_loggers [pool ('127.0.0.1', 8000)][conn #1] connection checked out of pool
get_socket checkout: SocketInfo(<socket.socket fd=7, id=0x7feb5604ad00>) at 0x7feb55eb3d00
_close_socket: SocketInfo(<socket.socket fd=7, id=0x7feb5604ad00>) at 0x7feb55eb3d00
get_socket checkout error: SocketInfo(<socket.socket fd=-1, id=0x7feb5604ad00>) CLOSED at 0x7feb55eb3d00: 127.0.0.1:8000: connection closed
2021-06-10 11:22:31,207 INFO event_loggers [pool ('127.0.0.1', 8000)] pool cleared
return socket: SocketInfo(<socket.socket fd=-1, id=0x7feb5604ad00>) CLOSED at 0x7feb55eb3d00
2021-06-10 11:22:31,207 INFO event_loggers [pool ('127.0.0.1', 8000)][conn #1] connection checked into pool
2021-06-10 11:22:31,208 INFO event_loggers [pool ('127.0.0.1', 8000)][conn #1] connection closed, reason: error
server.pool after error: deque([])
2021-06-10 11:22:31,208 INFO event_loggers [pool ('127.0.0.1', 8000)] connection check out started
2021-06-10 11:22:31,209 INFO event_loggers [pool ('127.0.0.1', 8000)][conn #2] connection created
2021-06-10 11:22:31,211 INFO event_loggers [pool ('127.0.0.1', 8000)][conn #2] connection setup succeeded
2021-06-10 11:22:31,211 INFO event_loggers [pool ('127.0.0.1', 8000)][conn #2] connection checked out of pool
get_socket checkout: SocketInfo(<socket.socket fd=7, id=0x7feb5652e6a0>) at 0x7feb55b27940
server.pool after success: deque([])
Created _SocketManager: SocketInfo(<socket.socket fd=7, id=0x7feb5652e6a0>) at 0x7feb55b27940
get_socket: SocketInfo(<socket.socket fd=6, id=0x7feb56159280>) at 0x7feb4ad90f70
return socket: SocketInfo(<socket.socket fd=6, id=0x7feb56159280>) at 0x7feb4ad90f70
sockets.appendleft: SocketInfo(<socket.socket fd=6, id=0x7feb56159280>) at 0x7feb4ad90f70
sock: SocketInfo(<socket.socket fd=7, id=0x7feb5652e6a0>) at 0x7feb55b27940
Pool before cursor del: deque([])
Pool after cursor del: deque([])
gc: collectable <Cursor 0x7feb561e6850>
gc: collectable <dict 0x7feb56525940>
gc: collectable <Collection 0x7feb4c7231c0>
gc: collectable <dict 0x7feb56525880>
gc: collectable <Database 0x7feb4c7234f0>
gc: collectable <CodecOptions 0x7feb561d3d60>
gc: collectable <dict 0x7feb561e1500>
gc: collectable <_ServerSession 0x7feb561946d0>
gc: collectable <Binary 0x7feb561e97c0>
gc: collectable <dict 0x7feb56012f80>
gc: collectable <dict 0x7feb4c71fc40>
gc: collectable <SessionOptions 0x7feb55b15640>
gc: collectable <ClientSession 0x7feb55a51220>
gc: collectable <dict 0x7feb4c71ff00>
gc: collectable <_Transaction 0x7feb55d6eca0>
gc: collectable <_Query 0x7feb561bbd50>
gc: collectable <method 0x7feb561ed040>
gc: collectable <cell 0x7feb55d6ec40>
gc: collectable <cell 0x7feb55baa610>
gc: collectable <cell 0x7feb55eb31f0>
gc: collectable <cell 0x7feb55eb3580>
gc: collectable <tuple 0x7feb561e96d0>
gc: collectable <function 0x7feb55de3d30>
gc: collectable <function 0x7feb55eb4af0>
gc: collectable <frame 0x7feb56347670>
gc: collectable <frame 0x7feb558cc8c0>
gc: collectable <_MongoClientErrorHandler 0x7feb561e2940>
gc: collectable <frame 0x7feb558cd640>
gc: collectable <socket 0x7feb5604ad00>
gc: collectable <SocketInfo 0x7feb55eb3d00>
gc: collectable <dict 0x7feb55ef5cc0>
gc: collectable <set 0x7feb5618e660>
gc: collectable <SocketChecker 0x7feb55eb3c70>
gc: collectable <SON 0x7feb56065c20>
gc: collectable <dict 0x7feb4dc27580>
gc: collectable <list 0x7feb4c724100>
gc: collectable <tuple 0x7feb4c71fd80>
gc: collectable <tuple 0x7feb4c71fe00>
gc: collectable <managedbuffer 0x7feb55b1c140>
gc: collectable <memoryview 0x7feb5603be80>
gc: collectable <tuple 0x7feb55a9bd60>
gc: collectable <OSError 0x7feb5650d2c0>
gc: collectable <traceback 0x7feb5610ca80>
gc: collectable <frame 0x7feb55f8b970>
gc: collectable <traceback 0x7feb5610cb00>
gc: collectable <frame 0x7feb55f8b610>
gc: collectable <traceback 0x7feb5610c540>
gc: collectable <AutoReconnect 0x7feb55392e20>
gc: collectable <tuple 0x7feb55e88f70>
gc: collectable <set 0x7feb5618e820>
gc: collectable <dict 0x7feb53499280>
gc: collectable <list 0x7feb4c71fdc0>
gc: collectable <traceback 0x7feb4c1b2e40>
gc: collectable <frame 0x7feb56532950>
gc: collectable <traceback 0x7feb5610c640>
gc: collectable <frame 0x7feb56538ac0>
gc: collectable <traceback 0x7feb5610c500>
gc: collectable <frame 0x7feb561f5040>
gc: collectable <traceback 0x7feb5610c580>
gc: collectable <frame 0x7feb56479d50>
gc: collectable <traceback 0x7feb5610c880>
gc: collectable <frame 0x7feb561eea40>
gc: collectable <traceback 0x7feb561e7dc0>
gc: collectable <traceback 0x7feb561e7b00>
gc: collectable <traceback 0x7feb561e1d00>
gc: collectable <traceback 0x7feb561e1480>
gc: collectable <socket 0x7feb5652e6a0>
gc: collectable <SocketInfo 0x7feb55b27940>
gc: collectable <dict 0x7feb4c724180>
gc: collectable <set 0x7feb5618e900>
gc: collectable <SocketChecker 0x7feb55d9afd0>
gc: collectable <ObjectId 0x7feb561e6d30>
gc: collectable <_OpMsg 0x7feb5616cb40>
gc: collectable <list 0x7feb56192e80>
gc: collectable <list 0x7feb56067200>
gc: collectable <ObjectId 0x7feb55b04970>
gc: collectable <dict 0x7feb56525b80>
gc: collectable <ObjectId 0x7feb561e67f0>
gc: collectable <dict 0x7feb56525b00>
gc: collectable <ObjectId 0x7feb561e65e0>
gc: collectable <dict 0x7feb56525700>
gc: collectable <ObjectId 0x7feb561e6520>
gc: collectable <dict 0x7feb565258c0>
gc: collectable <ObjectId 0x7feb561e65b0>
gc: collectable <dict 0x7feb56525980>
gc: collectable <dict 0x7feb4c716dc0>
gc: collectable <Int64 0x7feb56525a80>
gc: collectable <dict 0x7feb56155300>
gc: collectable <Timestamp 0x7feb561e6ca0>
gc: collectable <PinnedResponse 0x7feb5652e8e0>
gc: collectable <frame 0x7feb563429a0>
gc: collectable <frame 0x7feb56341dd0>
gc: collectable <_SocketManager 0x7feb55eb3820>
gc: collectable <dict 0x7feb5500e800>
gc: collectable <collections.deque 0x7feb56112e20>
gc: collectable <frame 0x7feb56341770>
gc: collectable <frame 0x7feb5633e000>
gc: collectable <frame 0x7feb56533ba0>
Cursor.__die
_SocketManager.close: SocketInfo(<socket.socket fd=7, id=0x7feb5652e6a0>) at 0x7feb55b27940
return socket: SocketInfo(<socket.socket fd=7, id=0x7feb5652e6a0>) at 0x7feb55b27940
2021-06-10 11:22:31,245 INFO event_loggers [pool ('127.0.0.1', 8000)][conn #2] connection checked into pool
sockets.appendleft: SocketInfo(<socket.socket fd=7, id=0x7feb5652e6a0>) at 0x7feb55b27940
_SocketManager.__del__: None
/Users/shane/git/mongo-python-driver/test/load_balancer/test_load_balancer.py:99: ResourceWarning: unclosed <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 59545), raddr=('127.0.0.1', 8000)>
  gc.collect()
Object allocated at (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/suite.py", lineno 84
    return self.run(*args, **kwds)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/suite.py", lineno 122
    test(result)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/suite.py", lineno 84
    return self.run(*args, **kwds)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/suite.py", lineno 122
    test(result)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/suite.py", lineno 84
    return self.run(*args, **kwds)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/suite.py", lineno 122
    test(result)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py", lineno 736
    return self.run(*args, **kwds)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py", lineno 676
    self._callTestMethod(testMethod)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py", lineno 633
    method()
  File "/Users/shane/git/mongo-python-driver/test/load_balancer/test_load_balancer.py", lineno 83
    next(cursor)
  File "/Users/shane/git/mongo-python-driver/pymongo/cursor.py", lineno 1237
    if len(self.__data) or self._refresh():
  File "/Users/shane/git/mongo-python-driver/pymongo/cursor.py", lineno 1158
    self.__send_message(q)
  File "/Users/shane/git/mongo-python-driver/pymongo/cursor.py", lineno 1046
    response = client._run_operation(
  File "/Users/shane/git/mongo-python-driver/pymongo/mongo_client.py", lineno 1289
    return self._retryable_read(
  File "/Users/shane/git/mongo-python-driver/pymongo/mongo_client.py", lineno 1391
    with self._slaveok_for_server(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/contextlib.py", lineno 113
    return next(self.gen)
  File "/Users/shane/git/mongo-python-driver/pymongo/mongo_client.py", lineno 1235
    with self._get_socket(server, session, pin=pin) as sock_info:
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/contextlib.py", lineno 113
    return next(self.gen)
  File "/Users/shane/git/mongo-python-driver/pymongo/mongo_client.py", lineno 1171
    with server.get_socket(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/contextlib.py", lineno 113
    return next(self.gen)
  File "/Users/shane/git/mongo-python-driver/pymongo/pool.py", lineno 1375
    sock_info = self._get_socket(all_credentials)
  File "/Users/shane/git/mongo-python-driver/pymongo/pool.py", lineno 1498
    sock_info = self.connect(all_credentials)
  File "/Users/shane/git/mongo-python-driver/pymongo/pool.py", lineno 1324
    sock = _configured_socket(self.address, self.opts)
  File "/Users/shane/git/mongo-python-driver/pymongo/pool.py", lineno 1021
    sock = _create_connection(address, options)
  File "/Users/shane/git/mongo-python-driver/pymongo/pool.py", lineno 983
    sock = socket.socket(
gc: collectable <tuple 0x7feb5655cf70>
gc: collectable <type 0x7feb56605d30>
gc: collectable <getset_descriptor 0x7feb56570580>
gc: collectable <dict 0x7feb56525fc0>
gc: collectable <tuple 0x7feb56564630>
gc: collectable <tuple 0x7feb565680d0>
gc: collectable <type 0x7feb56606430>
gc: collectable <tuple 0x7feb5656ccc0>
gc: collectable <tuple 0x7feb56568160>
gc: collectable <type 0x7feb56606aa0>
gc: collectable <tuple 0x7feb5656cef0>
Pool after gc.collect: deque([SocketInfo(<socket.socket fd=-1, id=0x7feb5652e6a0>) at 0x7feb55b27940])
hello
2021-06-10 11:22:31,296 INFO event_loggers [pool ('127.0.0.1', 8000)] connection check out started
2021-06-10 11:22:31,297 INFO event_loggers [pool ('127.0.0.1', 8000)][conn #2] connection checked out of pool
get_socket: SocketInfo(<socket.socket fd=-1, id=0x7feb5652e6a0>) at 0x7feb55b27940
_close_socket: SocketInfo(<socket.socket fd=-1, id=0x7feb5652e6a0>) at 0x7feb55b27940
get_socket error: SocketInfo(<socket.socket fd=-1, id=0x7feb5652e6a0>) CLOSED at 0x7feb55b27940
2021-06-10 11:22:31,298 INFO event_loggers [pool ('127.0.0.1', 8000)] pool cleared
return socket: SocketInfo(<socket.socket fd=-1, id=0x7feb5652e6a0>) CLOSED at 0x7feb55b27940
2021-06-10 11:22:31,299 INFO event_loggers [pool ('127.0.0.1', 8000)][conn #2] connection checked into pool
2021-06-10 11:22:31,299 INFO event_loggers [pool ('127.0.0.1', 8000)][conn #2] connection closed, reason: error
ERROR

======================================================================
ERROR: test_watch_leak (test_load_balancer.TestLB)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/shane/git/mongo-python-driver/pymongo/pool.py", line 714, in command
    return command(self, dbname, spec, slave_ok,
  File "/Users/shane/git/mongo-python-driver/pymongo/network.py", line 142, in command
    sock_info.sock.sendall(msg)
OSError: [Errno 9] Bad file descriptor

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/shane/git/mongo-python-driver/test/load_balancer/test_load_balancer.py", line 103, in test_watch_leak
    print(client.admin.command('hello')['ok'])
  File "/Users/shane/git/mongo-python-driver/pymongo/database.py", line 604, in command
    return self._command(sock_info, command, slave_ok, value,
  File "/Users/shane/git/mongo-python-driver/pymongo/database.py", line 486, in _command
    return sock_info.command(
  File "/Users/shane/git/mongo-python-driver/pymongo/pool.py", line 730, in command
    self._raise_connection_failure(error)
  File "/Users/shane/git/mongo-python-driver/pymongo/pool.py", line 923, in _raise_connection_failure
    _raise_connection_failure(self.address, error)
  File "/Users/shane/git/mongo-python-driver/pymongo/pool.py", line 249, in _raise_connection_failure
    raise AutoReconnect(msg) from error
pymongo.errors.AutoReconnect: 127.0.0.1:8000: [Errno 9] Bad file descriptor