Fixup: select on closed socket causes ValueError
ERROR: test_exhaust_getmore_network_error (test.test_client.TestExhaustCursor)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/shane/git/mongo-python-driver/test/test_client.py", line 1639, in test_exhaust_getmore_network_error
    self.assertRaises(ConnectionFailure, list, cursor)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py", line 816, in assertRaises
    return context.handle('assertRaises', args, kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py", line 202, in handle
    callable_obj(*args, **kwargs)
  File "/Users/shane/git/mongo-python-driver/pymongo/cursor.py", line 1156, in next
    if len(self.__data) or self._refresh():
  File "/Users/shane/git/mongo-python-driver/pymongo/cursor.py", line 1093, in _refresh
    self.__send_message(g)
  File "/Users/shane/git/mongo-python-driver/pymongo/cursor.py", line 953, in __send_message
    response = client._run_operation_with_response(
  File "/Users/shane/git/mongo-python-driver/pymongo/mongo_client.py", line 1325, in _run_operation_with_response
    return server.run_operation_with_response(
  File "/Users/shane/git/mongo-python-driver/pymongo/server.py", line 119, in run_operation_with_response
    reply = sock_info.receive_message(None)
  File "/Users/shane/git/mongo-python-driver/pymongo/pool.py", line 651, in receive_message
    self._raise_connection_failure(error)
  File "/Users/shane/git/mongo-python-driver/pymongo/pool.py", line 648, in receive_message
    return receive_message(self.sock, request_id,
  File "/Users/shane/git/mongo-python-driver/pymongo/network.py", line 196, in receive_message
    _receive_data_on_socket(sock, 16))
  File "/Users/shane/git/mongo-python-driver/pymongo/network.py", line 271, in _receive_data_on_socket
    chunk_length = _recv_into(sock, mv[bytes_read:])
  File "/Users/shane/git/mongo-python-driver/pymongo/network.py", line 262, in _recv_into
    _wait_for_read(sock)
  File "/Users/shane/git/mongo-python-driver/pymongo/network.py", line 226, in _wait_for_read
    rd, _, exc = select.select([sock], [], [sock], timeout)
ValueError: file descriptor cannot be a negative integer (-1)