Fix mypy bson
Remove unused import
gridfs/grid_file.py:26: error: Module 'bson.py3compat' has no attribute 'StringIO'
pymongo/helpers.py:20: error: Module 'bson.py3compat' has no attribute 'abc'