PYTHON-4310 server_selector cannot return arbitray servers
pymongo.errors.ConfigurationError: Custom server_selector is invalid because it returned a ServerDescription that was not supplied to it, server_selector: <function server_selector at 0x11b39fd80>, given servers: [<ServerDescription ('localhost', 27019) server_type: RSPrimary, rtt: 0.001381541951559484>], returned servers: [<ServerDescription ('localhost', 27019) server_type: Unknown, rtt: None>]